CREATE TABLE `tra_split` (
  `split_id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(50) NOT NULL,
  `split_date` DATE NOT NULL,
  `split_factor` DECIMAL(19,12) NOT NULL,
  PRIMARY KEY (`split_id`)
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0;
ALTER TABLE `tra_split` ADD UNIQUE INDEX `tra_split_idx1` (`symbol`, `split_date`);
