ALTER TABLE `tra_company` ADD COLUMN `mf_cnt` INTEGER(11) DEFAULT NULL;
ALTER TABLE `tra_company` ADD COLUMN `mf_qty` INTEGER(11) DEFAULT NULL;
ALTER TABLE `tra_company` MODIFY COLUMN `mf_qty` DECIMAL(13,4) DEFAULT NULL;
