CREATE TABLE `tra_market_intra_day` (
  `symbol` VARCHAR(50) NOT NULL,
  `trade_date` DATETIME(6) NOT NULL,
  `ltp_price` DECIMAL(13,4) NOT NULL,
  PRIMARY KEY (`symbol`, `trade_date`)
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0;