CREATE TABLE `tra_rsi_profit` (
  `rsi_profit_id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(20) NOT NULL,
  `buy_rsi` DECIMAL(13,4) DEFAULT NULL,
  `sell_rsi` DECIMAL(13,4) DEFAULT NULL,
  `buy_price` DECIMAL(13,4) DEFAULT NULL,
  `sell_price` DECIMAL(13,4) DEFAULT NULL,
  `buy_date` DATE DEFAULT NULL,
  `sell_date` DATE DEFAULT NULL,
  `profit` DECIMAL(13,4) DEFAULT NULL,
  PRIMARY KEY (`rsi_profit_id`)
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0;