ALTER TABLE `tra_market` ADD COLUMN `prev_ltp_price` INTEGER(11) DEFAULT NULL;
CREATE TABLE `tra_prev_calc` (
  `prev_calc_id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(50) NOT NULL,
  `positive_count` INTEGER(11) DEFAULT NULL,
  `negative_count` INTEGER(11) DEFAULT NULL,
  `open_profit` DECIMAL(13,4) DEFAULT NULL,
  `high_profit` DECIMAL(13,4) DEFAULT NULL,
  `success_count` INTEGER(11) DEFAULT NULL,
  `fail_count` INTEGER(11) DEFAULT NULL,
  PRIMARY KEY (`prev_calc_id`)
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0;
ALTER TABLE `tra_market` MODIFY COLUMN `prev_ltp_price` DECIMAL(13,4) DEFAULT NULL;
CREATE TABLE `tra_pre_calc_item` (
  `prev_calc_item_id` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `percentage` INTEGER(11) DEFAULT NULL,
  `success_count` INTEGER(11) DEFAULT NULL,
  `fail_count` INTEGER(11) DEFAULT NULL,
  PRIMARY KEY (`prev_calc_item_id`)
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0;